[project]
name = "lab10"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cvxopt>=1.3.2",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pyqt5>=5.15.11",
    "scipy>=1.16.3",
    "statsmodels>=0.14.6",
]
